#include <gtest/gtest.h>

#include "ingest/video_ingest_node.hpp"
#include "shm/shm_circular_buffer.hpp"
#include "shm/shm_mapping.hpp"
#include "common/constants/video_constants.hpp"
#include "common/runtime_defaults.hpp"
#include "common/oe_logger.hpp"

#include <array>
#include <atomic>
#include <chrono>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <thread>
#include <vector>

#include <sys/mman.h>   // shm_unlink

#include <spdlog/spdlog.h>

// ---------------------------------------------------------------------------
// OmniEdge_AI — Video Pipeline End-to-End Integration Test
//
// Feeds REAL video files through the actual VideoIngestNode GStreamer
// pipeline → SHM circular buffer path.  Validates:
//   - Frames actually decode and arrive in SHM
//   - Frame data is non-zero (not black/corrupt)
//   - Throughput meets minimum FPS targets
//   - Multiple resolutions and framerates work correctly
//   - No frame data corruption (consistent frame size)
//
// Prerequisites:
//   - GStreamer runtime installed (gst-launch-1.0, decodebin, videoconvert)
//   - Test media generated by: tests/integration/pipeline/download_test_media.sh
//   - OR: ffmpeg available for on-the-fly synthetic video generation
//
// Test media location: tests/integration/pipeline/data/
// ---------------------------------------------------------------------------


namespace {

namespace fs = std::filesystem;
using Clock = std::chrono::steady_clock;

// Test media directory — absolute path derived from __FILE__ at compile time.
// This ensures the path resolves correctly regardless of the working directory
// (ctest runs from the build tree, not the source tree).
const fs::path kTestDataDir = fs::path(__FILE__).parent_path() / "data";

/// Generate a synthetic test video with ffmpeg if it doesn't exist.
/// Returns true if the file exists (or was created), false on failure.
bool ensureTestVideo(const fs::path& path, uint32_t width, uint32_t height,
                     uint32_t fps, uint32_t durationSec)
{
    if (fs::exists(path)) {
        SPDLOG_DEBUG("test_video_exists: path={}, size={} bytes",
            path.string(), fs::file_size(path));
        return true;
    }

    // Create parent directories
    fs::create_directories(path.parent_path());

    // Generate synthetic video with ffmpeg testsrc2 pattern
    const std::string cmd = std::format(
        "ffmpeg -y -f lavfi "
        "-i \"testsrc2=size={}x{}:rate={}:duration={}\" "
        "-c:v libx264 -preset ultrafast -crf 18 "
        "-pix_fmt yuv420p "
        "\"{}\" 2>/dev/null",
        width, height, fps, durationSec, path.string());

    SPDLOG_INFO("generating_test_video: cmd={}", cmd);
    const int ret = std::system(cmd.c_str());
    if (ret != 0 || !fs::exists(path)) {
        SPDLOG_ERROR("ffmpeg_generate_failed: ret={}, path={}", ret, path.string());
        return false;
    }
    SPDLOG_INFO("test_video_generated: path={}, size={} bytes",
        path.string(), fs::file_size(path));
    return true;
}

/// Run VideoIngestNode with a file source for a duration, collecting frame
/// stats from the SHM consumer side.
struct PipelineResult {
    uint64_t framesReceived = 0;
    double   elapsedSec     = 0.0;
    double   avgFps         = 0.0;
    double   minFrameTimeMs = 1e9;
    double   maxFrameTimeMs = 0.0;
    uint64_t corruptFrames  = 0;   ///< Frames with all-zero data
    bool     pipelineError  = false;
};

PipelineResult runVideoPipeline(const fs::path& videoPath,
                                uint32_t width, uint32_t height,
                                double   maxRuntimeSec)
{
    PipelineResult result;

    // Clean up any stale SHM segment from previous tests to prevent
    // SIGBUS from size mismatch (different tests use different resolutions).
    shm_unlink("/oe.vid.ingest");

    // Configure VideoIngestNode with test ports and file source
    VideoIngestNode::Config cfg;
    cfg.v4l2Device      = videoPath.string();  // triggers filesrc path
    cfg.frameWidth      = width;
    cfg.frameHeight     = height;
    cfg.pubPort         = 25555;   // +20000 offset
    cfg.wsBridgeSubPort = 25570;
    cfg.moduleName      = "video_ingest_e2e_test";

    VideoIngestNode node(cfg);

    // Initialize transport (SHM + ZMQ)
    auto transportResult = node.configureTransport();
    if (!transportResult) {
        SPDLOG_ERROR("configureTransport_failed: {}", transportResult.error());
        result.pipelineError = true;
        return result;
    }

    // Build GStreamer pipeline (filesrc + decodebin)
    auto inferResult = node.loadInferencer();
    if (!inferResult) {
        SPDLOG_ERROR("loadInferencer_failed: {}", inferResult.error());
        result.pipelineError = true;
        return result;
    }

    // Open SHM as consumer to read frames
    const std::size_t frameBytes =
        static_cast<std::size_t>(width) * height * 3u;
    constexpr uint32_t kSlots = kCircularBufferSlotCount;  // 4

    ShmCircularBuffer<ShmVideoHeader> consumer(
        "/oe.vid.ingest", kSlots, frameBytes, /*create=*/false);

    // Start GStreamer pipeline (this begins delivering frames)
    node.onBeforeRun();

    SPDLOG_INFO("pipeline_started: file={}, resolution={}x{}, max_runtime={}s",
        videoPath.string(), width, height, maxRuntimeSec);

    // Keep a background thread alive while the pipeline runs.
    // GStreamer's appsink callback writes frames to SHM directly —
    // no MessageRouter polling is needed for the SHM consumer path.
    // This thread simply keeps the test alive until maxRuntimeSec elapses.
    std::atomic<bool> stopFlag{false};
    std::thread pollThread([&stopFlag]() {
        while (!stopFlag.load(std::memory_order_acquire)) {
            std::this_thread::sleep_for(std::chrono::milliseconds(5));
        }
    });

    // Consume frames from SHM
    const auto startTime = Clock::now();
    auto lastFrameTime = startTime;
    uint64_t lastSeq = 0;

    while (true) {
        const auto now = Clock::now();
        const double elapsed =
            std::chrono::duration<double>(now - startTime).count();

        if (elapsed >= maxRuntimeSec) {
            break;
        }

        auto slot = consumer.readLatestSlot();
        if (!slot.valid) {
            std::this_thread::sleep_for(std::chrono::microseconds(500));
            continue;
        }

        // Check if this is a new frame (sequence number advanced)
        const auto* hdr = consumer.header();
        const uint64_t seq = hdr->seqNumber;
        if (seq == lastSeq) {
            std::this_thread::sleep_for(std::chrono::microseconds(500));
            continue;
        }

        lastSeq = seq;
        result.framesReceived++;

        // Measure inter-frame timing
        const double frameTimeMs =
            std::chrono::duration<double, std::milli>(now - lastFrameTime).count();
        if (result.framesReceived > 1) {
            result.minFrameTimeMs = std::min(result.minFrameTimeMs, frameTimeMs);
            result.maxFrameTimeMs = std::max(result.maxFrameTimeMs, frameTimeMs);
        }
        lastFrameTime = now;

        // Check for corrupt (all-zero) frames — sample first 1024 bytes
        bool allZero = true;
        const std::size_t checkBytes = std::min(frameBytes, std::size_t{1024});
        for (std::size_t i = 0; i < checkBytes; ++i) {
            if (slot.data[i] != 0) {
                allZero = false;
                break;
            }
        }
        if (allZero) {
            result.corruptFrames++;
        }

        if (result.framesReceived % 30 == 0) {
            SPDLOG_DEBUG("frame_received: seq={}, slot={}, total={}, elapsed={:.2f}s",
                seq, slot.slot, result.framesReceived, elapsed);
        }
    }

    // Calculate final stats
    const auto endTime = Clock::now();
    result.elapsedSec =
        std::chrono::duration<double>(endTime - startTime).count();
    result.avgFps = (result.elapsedSec > 0.0)
        ? static_cast<double>(result.framesReceived) / result.elapsedSec
        : 0.0;

    SPDLOG_INFO("pipeline_result: frames={}, elapsed={:.2f}s, avg_fps={:.1f}, "
                "min_frame_ms={:.1f}, max_frame_ms={:.1f}, corrupt={}",
        result.framesReceived, result.elapsedSec, result.avgFps,
        result.minFrameTimeMs, result.maxFrameTimeMs, result.corruptFrames);

    // Shut down
    stopFlag.store(true, std::memory_order_release);
    node.onAfterStop();
    pollThread.join();

    // Clean up SHM segment so next test starts fresh
    shm_unlink("/oe.vid.ingest");

    return result;
}

} // anonymous namespace


// ===========================================================================
// Test: 1080p60 High-FPS Stress Test
// ===========================================================================

TEST(VideoPipelineE2E, Decode1080p60_FramesThroughSHM)
{
    const auto videoPath = kTestDataDir / "test_1080p60.mp4";
    if (!ensureTestVideo(videoPath, 1920, 1080, 60, 5)) {
        GTEST_SKIP() << "Could not generate test video (ffmpeg not available)";
    }

    auto result = runVideoPipeline(videoPath, 1920, 1080, /*maxRuntimeSec=*/6.0);

    ASSERT_FALSE(result.pipelineError) << "GStreamer pipeline failed to start";

    // Must receive at least some frames (file is 5s @ 60fps = ~300 frames)
    SPDLOG_INFO("1080p60_result: frames={}, fps={:.1f}", result.framesReceived, result.avgFps);
    EXPECT_GT(result.framesReceived, 30u)
        << "Expected at least 30 frames from a 5s 60fps video";

    // Average FPS should be reasonable (>20fps for decode + SHM write)
    EXPECT_GT(result.avgFps, 20.0)
        << "Decode throughput too low for 1080p60";

    // No corrupt frames
    EXPECT_EQ(result.corruptFrames, 0u)
        << "Detected all-zero (corrupt) frames in SHM output";
}

// ===========================================================================
// Test: 1080p30 Standard Production Config
// ===========================================================================

TEST(VideoPipelineE2E, Decode1080p30_StandardConfig)
{
    const auto videoPath = kTestDataDir / "test_1080p30.mp4";
    if (!ensureTestVideo(videoPath, 1920, 1080, 30, 5)) {
        GTEST_SKIP() << "Could not generate test video (ffmpeg not available)";
    }

    auto result = runVideoPipeline(videoPath, 1920, 1080, /*maxRuntimeSec=*/6.0);

    ASSERT_FALSE(result.pipelineError);
    SPDLOG_INFO("1080p30_result: frames={}, fps={:.1f}", result.framesReceived, result.avgFps);

    EXPECT_GT(result.framesReceived, 20u)
        << "Expected at least 20 frames from a 5s 30fps video";

    EXPECT_GT(result.avgFps, 15.0)
        << "Decode throughput too low for 1080p30";

    EXPECT_EQ(result.corruptFrames, 0u);
}

// ===========================================================================
// Test: 720p30 Reduced Resolution Baseline
// ===========================================================================

TEST(VideoPipelineE2E, Decode720p30_ReducedResolution)
{
    // Use a distinct filename with duration suffix to avoid clashes with
    // shorter clips generated by other tests.
    const auto videoPath = kTestDataDir / "test_720p30_5s.mp4";
    if (!ensureTestVideo(videoPath, 1280, 720, 30, 5)) {
        GTEST_SKIP() << "Could not generate test video (ffmpeg not available)";
    }

    auto result = runVideoPipeline(videoPath, 1280, 720, /*maxRuntimeSec=*/6.0);

    ASSERT_FALSE(result.pipelineError);
    SPDLOG_INFO("720p30_result: frames={}, fps={:.1f}", result.framesReceived, result.avgFps);

    EXPECT_GT(result.framesReceived, 20u)
        << "Expected at least 20 frames from a 5s 30fps video";

    // 720p should decode faster than 1080p
    EXPECT_GT(result.avgFps, 20.0)
        << "Decode throughput too low for 720p30";

    EXPECT_EQ(result.corruptFrames, 0u);
}

// ===========================================================================
// Test: Frame Data Integrity
//
// Verifies that frame pixel data is actually meaningful (not just random
// noise or repeated patterns).  Decodes a known test pattern and checks
// that the BGR data has reasonable statistics.
// ===========================================================================

TEST(VideoPipelineE2E, FrameDataIntegrity_NonTrivialPixels)
{
    shm_unlink("/oe.vid.ingest");  // Clean stale segment

    // Use a distinct filename — ShmHeaderResolutionCorrect also generates a
    // 720p30 clip but at 2 s duration.  Sharing one name causes the file
    // content to depend on test execution order.
    const auto videoPath = kTestDataDir / "test_720p30_3s.mp4";
    if (!ensureTestVideo(videoPath, 1280, 720, 30, 3)) {
        GTEST_SKIP() << "Could not generate test video (ffmpeg not available)";
    }

    // Configure with smaller resolution for faster processing
    VideoIngestNode::Config cfg;
    cfg.v4l2Device      = videoPath.string();
    cfg.frameWidth      = 640;
    cfg.frameHeight     = 480;
    cfg.pubPort         = 25755;  // different port to avoid clash
    cfg.wsBridgeSubPort = 25770;
    cfg.moduleName      = "video_ingest_integrity_test";

    VideoIngestNode node(cfg);
    auto tr = node.configureTransport();
    ASSERT_TRUE(tr.has_value()) << tr.error();
    auto lr = node.loadInferencer();
    ASSERT_TRUE(lr.has_value()) << lr.error();

    const std::size_t frameBytes = 640u * 480u * 3u;
    constexpr uint32_t kSlots = kCircularBufferSlotCount;

    ShmCircularBuffer<ShmVideoHeader> consumer(
        "/oe.vid.ingest", kSlots, frameBytes, false);

    node.onBeforeRun();

    // Wait for at least one frame
    std::vector<uint8_t> capturedFrame(frameBytes, 0);
    bool gotFrame = false;
    const auto deadline = Clock::now() + std::chrono::seconds(5);

    while (Clock::now() < deadline) {
        auto slot = consumer.readLatestSlot();
        if (slot.valid && consumer.header()->seqNumber > 0) {
            std::memcpy(capturedFrame.data(), slot.data, frameBytes);
            gotFrame = true;
            SPDLOG_INFO("captured_frame: seq={}, slot={}",
                consumer.header()->seqNumber, slot.slot);
            break;
        }
        std::this_thread::sleep_for(std::chrono::milliseconds(10));
    }

    node.onAfterStop();
    shm_unlink("/oe.vid.ingest");  // Clean up

    ASSERT_TRUE(gotFrame) << "No frame received within 5 seconds";

    // Analyze pixel statistics
    uint64_t sum = 0;
    uint32_t uniqueValues = 0;
    bool seenNonZero = false;
    std::array<bool, 256> valuesSeen{};  // zero-initialized (all false)

    for (std::size_t i = 0; i < frameBytes; ++i) {
        const uint8_t v = capturedFrame[i];
        sum += v;
        if (!valuesSeen[v]) {
            valuesSeen[v] = true;
            uniqueValues++;
        }
        if (v != 0) seenNonZero = true;
    }

    const double avgPixel = static_cast<double>(sum) / static_cast<double>(frameBytes);

    SPDLOG_INFO("frame_stats: avg_pixel={:.1f}, unique_values={}, non_zero={}",
        avgPixel, uniqueValues, seenNonZero);

    // Frame should not be all black
    EXPECT_TRUE(seenNonZero) << "Frame is entirely black (all zeros)";

    // A test pattern should have diverse pixel values (at least 10 unique)
    EXPECT_GT(uniqueValues, 10u)
        << "Frame has too few unique pixel values — likely corrupt";

    // Average pixel value should be somewhere reasonable (not all 0 or all 255)
    EXPECT_GT(avgPixel, 10.0) << "Average pixel value suspiciously low";
    EXPECT_LT(avgPixel, 245.0) << "Average pixel value suspiciously high";
}

// ===========================================================================
// Test: SHM Header Consistency
//
// Verifies that the SHM video header is correctly populated with the
// configured resolution after pipeline startup.
// ===========================================================================

TEST(VideoPipelineE2E, ShmHeaderResolutionCorrect)
{
    shm_unlink("/oe.vid.ingest");  // Clean stale segment

    const auto videoPath = kTestDataDir / "test_720p30_2s.mp4";
    if (!ensureTestVideo(videoPath, 1280, 720, 30, 2)) {
        GTEST_SKIP() << "Could not generate test video";
    }

    VideoIngestNode::Config cfg;
    cfg.v4l2Device      = videoPath.string();
    cfg.frameWidth      = 1280;
    cfg.frameHeight     = 720;
    cfg.pubPort         = 25855;
    cfg.wsBridgeSubPort = 25870;
    cfg.moduleName      = "video_ingest_hdr_test";

    VideoIngestNode node(cfg);
    auto tr = node.configureTransport();
    ASSERT_TRUE(tr.has_value()) << tr.error();
    auto lr = node.loadInferencer();
    ASSERT_TRUE(lr.has_value()) << lr.error();

    const std::size_t frameBytes = 1280u * 720u * 3u;
    ShmCircularBuffer<ShmVideoHeader> consumer(
        "/oe.vid.ingest", kCircularBufferSlotCount, frameBytes, false);

    // Header should be set before pipeline starts (in configureTransport)
    const auto* hdr = consumer.header();
    EXPECT_EQ(hdr->width, 1280u);
    EXPECT_EQ(hdr->height, 720u);
    EXPECT_EQ(hdr->bytesPerPixel, 3u);

    SPDLOG_INFO("shm_header: width={}, height={}, bpp={}",
        hdr->width, hdr->height, hdr->bytesPerPixel);

    // Start and wait for a frame to verify seqNumber increments
    node.onBeforeRun();

    const auto deadline = Clock::now() + std::chrono::seconds(5);
    while (Clock::now() < deadline) {
        if (hdr->seqNumber > 0) break;
        std::this_thread::sleep_for(std::chrono::milliseconds(10));
    }

    EXPECT_GT(hdr->seqNumber, 0u)
        << "No frames written to SHM within 5 seconds";

    node.onAfterStop();
    shm_unlink("/oe.vid.ingest");  // Clean up
}
